#!/bin/bash

# Define command-line arguments

NAMESPACE=$1
RESOURCE_TYPE=$2
HEADER_FORMAT="\033[4m\033[1m%-20s | %-20s | %-40s | %-10s | %-10s\033[0m\033[0m"
ROW_FORMAT="\n%-20s | %-20s | %-40s | %-10s | %-10s"

printf "${HEADER_FORMAT}" "Resource" "Namespace" "Name" "CPU" "Memory"
# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line 
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  printf "${ROW_FORMAT}" "${RESOURCE_TYPE}" "${NAMESPACE}" "${NAME}" "${CPU}" "${MEMORY}" 
done
printf "\n"